version: "3.8"

services:
  api:
    image: his/api:latest
    container_name: api
    build: .
    volumes:
      - ./project:/app
      # - ./project/db.sqlite3:/app/db.sqlite3
    networks:
      - backnet
  
  web:
    image: nginx:latest
    container_name: nginx
    build: ./nginx
    ports:
      - 8888:80
    networks:
      - backnet
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/var/www/html/staticfiles
      - ./nginx/dist:/var/www/html/app

volumes:
  service-data:
  staticfiles:

networks:
  backnet: