# Generated by Django 4.2.7 on 2024-01-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expertise',
            field=models.CharField(blank=True, choices=[('orthopedics', 'ارتوپدی'), ('digestion', 'گوارش'), ('kidney', 'کلیه'), ('ear_nose_throat', 'گوش و حلق و بینی'), ('neurosurgery', 'جراحی اعصاب'), ('general_surgery', 'جراحی عمومی'), ('psychology', 'روانشناسی'), ('ophthalmology', 'چشم پزشکی'), ('heart', 'قلب'), ('rheumatology', 'روماتولوژی'), ('glands', 'غدد'), ('children', 'اطفال'), ('infectious_diseases', 'بیماری های عفونی'), ('blood', 'خون'), ('skin', 'پوست'), ('dental', 'دندانپزشکی'), ('laboratory', 'آزمایشگاه'), ('photography', 'تصویربرداری')], max_length=200),
        ),
    ]
