# Generated by Django 4.2.7 on 2024-01-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'ادمین'), ('doctor', 'دکنر'), ('patient', 'بیمار'), ('nurse', 'پرستار'), ('pharmacy', 'داروخانه')], max_length=20),
        ),
    ]
