# Generated by Django 4.2.7 on 2024-01-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='attend_time',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
