# Generated by Django 4.2.7 on 2024-01-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dose', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=200)),
                ('expire_date', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
