# Generated by Django 4.2.7 on 2024-01-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dose',
            field=models.IntegerField(),
        ),
    ]
