# Generated by Django 4.2.7 on 2023-11-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_customuser_email_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('insurance_type', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('national_id', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('sex', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Trans')])),
            ],
        ),
    ]
