# Generated by Django 4.2.7 on 2023-11-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=500)),
                ('drug_sensitive', models.CharField(max_length=500)),
            ],
        ),
    ]
